// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YaroshenkoShop.Data;

#nullable disable

namespace YaroshenkoShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260107092824_FixIdentityUser")]
    partial class FixIdentityUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YaroshenkoShop.Models.BuyHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Gameid_игры")
                        .HasColumnType("int");

                    b.Property<int>("KeyId")
                        .HasColumnType("int")
                        .HasColumnName("id_ключ");

                    b.Property<DateTime?>("PurchaseTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("время_покупки");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("id_пользователь");

                    b.HasKey("id");

                    b.HasIndex("Gameid_игры");

                    b.HasIndex("KeyId");

                    b.HasIndex("UserId");

                    b.ToTable("BuyHistory", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Developer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("разработчик")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("разработчик");

                    b.HasKey("id");

                    b.ToTable("Developer", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Favorite", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("id_игры");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("id_пользователя");

                    b.HasKey("id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Game", b =>
                {
                    b.Property<int>("id_игры")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_игры");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_игры"));

                    b.Property<int?>("id_разработчика")
                        .HasColumnType("int")
                        .HasColumnName("id_разработчика");

                    b.Property<string>("год_выпуска")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("год_выпуска");

                    b.Property<string>("изображение")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("изображение");

                    b.Property<string>("название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("название");

                    b.Property<string>("описание")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("описание");

                    b.Property<decimal?>("цена")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("цена");

                    b.HasKey("id_игры");

                    b.HasIndex("id_разработчика");

                    b.ToTable("Games", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("YaroshenkoShop.Models.GameGenre", b =>
                {
                    b.Property<int>("id_игры")
                        .HasColumnType("int")
                        .HasColumnName("id_игры");

                    b.Property<int>("id_жанра")
                        .HasColumnType("int")
                        .HasColumnName("id_жанра");

                    b.Property<int>("id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.HasKey("id_игры", "id_жанра");

                    b.HasIndex("id_жанра");

                    b.ToTable("GameGenres", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("жанр")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("жанр");

                    b.HasKey("id");

                    b.ToTable("Genres", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Key", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("id_игры")
                        .HasColumnType("int")
                        .HasColumnName("id_игры");

                    b.Property<string>("ключ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ключ");

                    b.Property<bool?>("продан")
                        .HasColumnType("bit")
                        .HasColumnName("продан");

                    b.HasKey("id");

                    b.HasIndex("id_игры");

                    b.ToTable("Keys", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("YaroshenkoShop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("имя");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("YaroshenkoShop.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("YaroshenkoShop.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YaroshenkoShop.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("YaroshenkoShop.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YaroshenkoShop.Models.BuyHistory", b =>
                {
                    b.HasOne("YaroshenkoShop.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("Gameid_игры")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YaroshenkoShop.Models.Key", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YaroshenkoShop.Models.User", "User")
                        .WithMany("BuyHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Key");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Favorite", b =>
                {
                    b.HasOne("YaroshenkoShop.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YaroshenkoShop.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Game", b =>
                {
                    b.HasOne("YaroshenkoShop.Models.Developer", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("id_разработчика")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("YaroshenkoShop.Models.GameGenre", b =>
                {
                    b.HasOne("YaroshenkoShop.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("id_жанра")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YaroshenkoShop.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("id_игры")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Key", b =>
                {
                    b.HasOne("YaroshenkoShop.Models.Game", "Game")
                        .WithMany("Keys")
                        .HasForeignKey("id_игры")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Developer", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("Keys");
                });

            modelBuilder.Entity("YaroshenkoShop.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("YaroshenkoShop.Models.User", b =>
                {
                    b.Navigation("BuyHistory");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
